//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string XPATTERN = "xpattern";
        
        public const string OPATTERN = "opattern";
        
        public const string ZIGZAGPATTERN = "zigzagpattern";
        
        public const string SPATTERN = "spattern";
        
        public const string LOOPPATTERN = "looppattern";
    }
}
